|              URL               | Method | Why?                                               |                                                                       Request                                                                      |                                                                                  Response Data                                                                                     | Codes                                    |
|:------------------------------:|:------:|----------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|------------------------------------------|
| '/foodBot/profile/:id'            | GET    | Retrieve user info                                 | No data                                                                                                                                            | { username: String, restrictions: Array, allergins: String, match: String }                                                                                                        | 200, OK 404, Not found                   |
| '/foodBot/profile'               | GET    | Retrive all users                                  | No data                                                                                                                                            | [ {username: String, restrictions: Array, allergins: String, match: String } ]
| '/foodBot/auth/signup'         | POST   | Create a new                                   | { username: String, password: String, restrictions: Array, allergins: Array }                                                                      | Status Code                                                                                                                                                                        | 200, OK 403, Forbidden                   |
| '/foodBot/auth/signin'         | POST   | User signs in                                      | { username: String, password: String }                                                                                                             | Status Code                                                                                                                                                                        | 200, OK 401, Unauthorized                |
| '/foodBot/auth/signout'        | POST   | User signs out                                     | { username: String, password: String }                                                                                                             | Status Code                                                                                                                                                                        | 200, OK 401, Unauthorized                |
| '/foodBot/auth/signedin'       | GET    | Check user authorization                           | No data                                                                                                                                            | Status Code                                                                                                                                                                        | 200, OK 401, Unauthorized                |
|                                |        |                                                    |                                                                                                                                                    |                                                                                                                                                                                    |                                          |
| '/foodBot/recipes/'            | POST   | Add a new meal to the database                     | {userId: String, name: String, ingredients: Array, directions: String, timetocook: Number , region String}                                         | Status Code                                                                                                                                                                        | 200, OK 401, Unauthorized                |
| '/foodBot/recipes/:id'         | GET    | Retrieve Num recipes that do not have ingredients  | {amount: Number}                                                                                                                                   | {recipes: Array Of Recipe Objects (ex: {name, ingredients, directions, timetocook, region })}                                                                                      | 200, OK                                  |
|                                |        | that are on user restrictions & allergens          |                                                                                                                                                    |                                                                                                                                                                                    |                                          |
|                                |        |                                                    |                                                                                                                                                    |                                                                                                                                                                                    |                                          |
| '/foodBot/dash/:id'            | GET    | Get all meals where a user is a creator or eaten   | No data                                                                                                                                            | { created: Array Of Recipe Objects , eaten: Array of Recipe Objects}                                                                                                               | 200, OK 404, Not found                   |
| '/foodBot/dash/:id'            | POST   | Add a meal to a users page                         | {mealID: String}                                                                                                                                   | No data                                                                                                                                                                            | 200, OK 404, Not found                   |
|                                |        |                                                    |                                                                                                                                                    |                                                                                                                                                                                    |                                          |
| '/foodBot/match/:username'     | GET    | Get all meals for match                            | No data                                                                                                                                            | { created: Array Of Recipe Objects , eaten: Array of Recipe Objects}                                                                                                               | 200, OK 404, Not found                   |
  